name: CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      
      # CONTINOUS INTEGRATION -------------->
      
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env: 
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
        run: python -m pytest --html=report.html

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with: 
          name: test-report
          path: report.html

      # CONTINOUS DELIVERY -------->

      - name: Build Docker image
        run: docker build -t agno-agent-ci-cd .

      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag agno-agent-ci-cd ${{ secrets.DOCKERHUB_USERNAME }}/agno-agent-ci-cd:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/agno-agent-ci-cd:latest






      


